// Whisper-compatible log-Mel front-end — the smart-turn v3 INPUT CONTRACT.
//
// smart-turn v3 is a Whisper-tiny encoder + a shallow classifier head, so its ONNX
// graph does not take audio: it takes the exact log-Mel spectrogram Whisper's own
// feature extractor produces. Pipecat's reference inference (inference.py in
// pipecat-ai/smart-turn) is, verbatim:
//
//     audio  = truncate_audio_to_last_n_seconds(audio, n_seconds=8)   # left-pad to 8s
//     inputs = WhisperFeatureExtractor(chunk_length=8)(
//                  audio, sampling_rate=16000, padding="max_length",
//                  max_length=8*16000, truncation=True, do_normalize=True)
//     session.run(None, {"input_features": inputs.input_features})    # [1, 80, 800]
//
// So this module reproduces that chain exactly, in TypeScript:
//
//   1. keep the LAST 8s at 16kHz, left-padded with zeros to exactly 128000 samples
//      (audio_utils.truncate_audio_to_last_n_seconds — pads at the BEGINNING, which
//      is what makes the feature extractor's own padding a no-op and the whole
//      normalization window deterministic);
//   2. zero-mean / unit-variance the waveform (do_normalize=True →
//      WhisperFeatureExtractor.zero_mean_unit_var_norm, over the full 8s buffer);
//   3. log-Mel: periodic Hann(400), hop 160, centered with REFLECT padding, power
//      spectrum, 80 slaney-scale/slaney-norm Mel filters over 0–8000Hz, log10 with a
//      1e-10 floor, drop the trailing frame (Whisper's `log_spec[:, :-1]`), clamp to
//      max−8, then (x+4)/4 → [80, 800].
//
// WHY THIS EXISTS AT ALL (su-lou.10.1): the previous adapter fed the model a raw
// nearest-neighbour resample of the segment (smart-turn.ts's old toModelInput). That
// is not the model's input space, so the classifier would have produced noise had it
// ever run. It never did — no provisioner existed — so nobody noticed. Provisioning
// the model without fixing the front-end would have shipped a stage that REPORTS
// `model` while emitting garbage verdicts, which is a worse failure than the honest
// heuristic it replaces.
//
// Pure and dependency-free on purpose: the DSP is unit-testable in `npm test` with no
// provisioned asset and no browser (whisper-mel.test.ts), including a conformance test
// against golden features generated by the canonical transformers.js implementation.

/** smart-turn v3 runs at 16kHz mono, like the VAD segments feeding it. */
export const SAMPLE_RATE = 16000;
/** Whisper front-end constants (WhisperFeatureExtractor defaults). */
export const N_FFT = 400;
export const HOP_LENGTH = 160;
export const N_MELS = 80;
/** smart-turn v3 uses `chunk_length=8`, so 8s → 800 frames of 80 mels. */
export const CHUNK_SECONDS = 8;
export const N_SAMPLES = CHUNK_SECONDS * SAMPLE_RATE; // 128000
export const N_FRAMES = N_SAMPLES / HOP_LENGTH; // 800

/** Matches numpy/transformers: variance floor inside the normalization sqrt. */
const NORM_EPS = 1e-7;
/** transformers' `spectrogram(mel_floor=1e-10)` — keeps log10 finite on silence. */
const MEL_FLOOR = 1e-10;

// ── FFT ────────────────────────────────────────────────────────────────────────
//
// n_fft is 400 = 2⁴·5², NOT a power of two, so a radix-2 kernel cannot be used and
// zero-padding to 512 would move every bin (the Mel bank is indexed by bin → Hz).
// This is a generic mixed-radix Cooley-Tukey decimation-in-time: at each level the
// size is split by its smallest prime factor, so 400 costs ≈ n·Σ(radices) = 400·18
// complex MACs per frame rather than the 400·201 a naive DFT would. One twiddle
// table of size n serves every level (W_m^j = W_n^{j·(n/m)}).

/** Smallest prime factor of `n` (n itself when prime). */
function smallestFactor(n: number): number {
  for (let f = 2; f * f <= n; f++) if (n % f === 0) return f;
  return n;
}

export class Fft {
  readonly n: number;
  private readonly cos: Float64Array;
  private readonly sin: Float64Array;
  private readonly outRe: Float64Array;
  private readonly outIm: Float64Array;
  // Combine scratch. Safe to share across recursion levels: a node's combine runs
  // only after all its children have finished theirs, so no two combines overlap.
  private readonly tmpRe: Float64Array;
  private readonly tmpIm: Float64Array;

  constructor(n: number) {
    if (!Number.isInteger(n) || n < 1) throw new Error(`FFT size must be a positive integer, got ${n}`);
    this.n = n;
    this.cos = new Float64Array(n);
    this.sin = new Float64Array(n);
    for (let j = 0; j < n; j++) {
      const angle = (-2 * Math.PI * j) / n;
      this.cos[j] = Math.cos(angle);
      this.sin[j] = Math.sin(angle);
    }
    this.outRe = new Float64Array(n);
    this.outIm = new Float64Array(n);
    this.tmpRe = new Float64Array(n);
    this.tmpIm = new Float64Array(n);
  }

  /**
   * Forward DFT (unnormalized). `re`/`im` are read, never written; the result lives
   * in the returned buffers, which are REUSED by the next call.
   */
  transform(re: Float64Array, im: Float64Array): { re: Float64Array; im: Float64Array } {
    if (re.length < this.n || im.length < this.n) throw new Error(`FFT input shorter than ${this.n}`);
    this.rec(re, im, 0, 1, 0, this.n);
    return { re: this.outRe, im: this.outIm };
  }

  private rec(inRe: Float64Array, inIm: Float64Array, inOff: number, inStride: number, outOff: number, n: number): void {
    if (n === 1) {
      this.outRe[outOff] = inRe[inOff];
      this.outIm[outOff] = inIm[inOff];
      return;
    }
    const r = smallestFactor(n);
    const m = n / r;
    // r sub-transforms over the decimated inputs x_q[t] = x[q + r·t].
    for (let q = 0; q < r; q++) {
      this.rec(inRe, inIm, inOff + q * inStride, inStride * r, outOff + q * m, m);
    }
    const step = this.n / n; // W_n^j lives at table index j·step

    // Radix-2 is the common case (400 = 2⁴·5² → four of the six levels): the
    // classic butterfly pair, which needs no scratch and no modulo.
    //   X[k]   = Y₀[k] + W_n^k·Y₁[k]
    //   X[k+m] = Y₀[k] − W_n^k·Y₁[k]   (because W_n^{k+m} = −W_n^k)
    if (r === 2) {
      for (let k = 0, t = 0; k < m; k++, t += step) {
        const i0 = outOff + k;
        const i1 = i0 + m;
        const ar = this.outRe[i0];
        const ai = this.outIm[i0];
        const br = this.outRe[i1];
        const bi = this.outIm[i1];
        const c = this.cos[t];
        const s = this.sin[t];
        const tr = br * c - bi * s;
        const ti = br * s + bi * c;
        this.outRe[i0] = ar + tr;
        this.outIm[i0] = ai + ti;
        this.outRe[i1] = ar - tr;
        this.outIm[i1] = ai - ti;
      }
      return;
    }

    // General radix: X[k] = Σ_q W_n^{qk} · Y_q[k mod m]. The twiddle index walks
    // by k·step with a single wrap test — `(q·k) % n` in the inner loop is the
    // single most expensive operation in the whole front-end otherwise.
    for (let k = 0, km = 0; k < n; k++) {
      const dt = k * step;
      let t = 0;
      let sr = 0;
      let si = 0;
      for (let q = 0; q < r; q++) {
        const yr = this.outRe[outOff + q * m + km];
        const yi = this.outIm[outOff + q * m + km];
        const c = this.cos[t];
        const s = this.sin[t];
        sr += yr * c - yi * s;
        si += yr * s + yi * c;
        t += dt;
        if (t >= this.n) t -= this.n;
      }
      this.tmpRe[k] = sr;
      this.tmpIm[k] = si;
      if (++km === m) km = 0;
    }
    for (let k = 0; k < n; k++) {
      this.outRe[outOff + k] = this.tmpRe[k];
      this.outIm[outOff + k] = this.tmpIm[k];
    }
  }
}

// ── Mel filter bank ────────────────────────────────────────────────────────────

/** Hz → Mel, "slaney" scale (transformers' `hertz_to_mel(..., mel_scale='slaney')`). */
export function hertzToMel(freq: number): number {
  const MIN_LOG_HERTZ = 1000.0;
  const MIN_LOG_MEL = 15.0;
  const LOGSTEP = 27.0 / Math.log(6.4);
  if (freq >= MIN_LOG_HERTZ) return MIN_LOG_MEL + Math.log(freq / MIN_LOG_HERTZ) * LOGSTEP;
  return (3.0 * freq) / 200.0;
}

/** Mel → Hz, "slaney" scale (inverse of {@link hertzToMel}). */
export function melToHertz(mel: number): number {
  const MIN_LOG_HERTZ = 1000.0;
  const MIN_LOG_MEL = 15.0;
  const LOGSTEP = Math.log(6.4) / 27.0;
  if (mel >= MIN_LOG_MEL) return MIN_LOG_HERTZ * Math.exp(LOGSTEP * (mel - MIN_LOG_MEL));
  return (200.0 * mel) / 3.0;
}

/**
 * One triangular Mel filter, stored SPARSELY (each filter touches a handful of the
 * 201 bins; a dense 201×80 matmul per frame would cost more than the FFT itself).
 */
interface MelFilter {
  /** First frequency bin with a non-zero weight. */
  start: number;
  /** Weights for bins [start, start + weights.length). */
  weights: Float64Array;
}

/**
 * Slaney-scale, slaney-normalized triangular Mel bank — transformers'
 * `mel_filter_bank(201, 80, 0.0, 8000.0, 16000, norm='slaney', mel_scale='slaney')`,
 * which is what WhisperFeatureExtractor builds.
 */
export function melFilterBank(
  numFrequencyBins: number,
  numMelFilters: number,
  minFrequency: number,
  maxFrequency: number,
  sampleRate: number,
): MelFilter[] {
  const melMin = hertzToMel(minFrequency);
  const melMax = hertzToMel(maxFrequency);
  // num_mel_filters + 2 equally-spaced points in the Mel domain → filter edges in Hz.
  const filterFreqs = new Float64Array(numMelFilters + 2);
  for (let j = 0; j < filterFreqs.length; j++) {
    filterFreqs[j] = melToHertz(melMin + ((melMax - melMin) * j) / (numMelFilters + 1));
  }
  // linspace(0, sampleRate/2, numFrequencyBins) — the centre frequency of each bin.
  const fftFreqs = new Float64Array(numFrequencyBins);
  const nyquist = Math.floor(sampleRate / 2);
  for (let i = 0; i < numFrequencyBins; i++) fftFreqs[i] = (nyquist * i) / (numFrequencyBins - 1);

  const filters: MelFilter[] = [];
  for (let j = 0; j < numMelFilters; j++) {
    const lo = filterFreqs[j];
    const mid = filterFreqs[j + 1];
    const hi = filterFreqs[j + 2];
    // Slaney normalization: constant energy per channel rather than per bin.
    const enorm = 2.0 / (hi - lo);
    const dense = new Float64Array(numFrequencyBins);
    let start = -1;
    let end = -1;
    for (let i = 0; i < numFrequencyBins; i++) {
      const down = (fftFreqs[i] - lo) / (mid - lo);
      const up = (hi - fftFreqs[i]) / (hi - mid);
      const w = Math.max(0, Math.min(down, up)) * enorm;
      dense[i] = w;
      if (w > 0) {
        if (start < 0) start = i;
        end = i;
      }
    }
    // An empty filter (possible only for a degenerate bank) stays empty rather than
    // silently widening — the caller's output is then a floor value, not a guess.
    if (start < 0) filters.push({ start: 0, weights: new Float64Array(0) });
    else filters.push({ start, weights: dense.slice(start, end + 1) });
  }
  return filters;
}

/** Periodic Hann window — transformers' `window_function(n, 'hann')` (periodic=True). */
export function hannWindow(n: number): Float64Array {
  const w = new Float64Array(n);
  for (let i = 0; i < n; i++) w[i] = 0.5 - 0.5 * Math.cos((2 * Math.PI * i) / n);
  return w;
}

// ── the front-end ──────────────────────────────────────────────────────────────

/**
 * Keep the LAST `nSamples` of `audio`, or left-pad it with zeros to that length —
 * pipecat's `truncate_audio_to_last_n_seconds`. The END of the segment is what
 * carries the end-of-utterance evidence, so the head is what gets dropped.
 */
export function fitToWindow(audio: Float32Array, nSamples: number = N_SAMPLES): Float32Array {
  if (audio.length === nSamples) return audio;
  const out = new Float32Array(nSamples);
  if (audio.length > nSamples) out.set(audio.subarray(audio.length - nSamples));
  else out.set(audio, nSamples - audio.length); // pad at the BEGINNING
  return out;
}

/**
 * Zero-mean, unit-variance the waveform — WhisperFeatureExtractor's
 * `zero_mean_unit_var_norm` under `do_normalize=True`. Because the window is already
 * exactly `N_SAMPLES` long (step 1 padded it), the attention mask is all-ones and the
 * statistics are taken over the whole buffer, matching the reference exactly.
 */
export function zeroMeanUnitVar(x: Float32Array): Float32Array {
  const n = x.length;
  if (n === 0) return x;
  let mean = 0;
  for (let i = 0; i < n; i++) mean += x[i];
  mean /= n;
  let variance = 0;
  for (let i = 0; i < n; i++) {
    const d = x[i] - mean;
    variance += d * d;
  }
  variance /= n;
  const scale = 1 / Math.sqrt(variance + NORM_EPS);
  const out = new Float32Array(n);
  for (let i = 0; i < n; i++) out[i] = (x[i] - mean) * scale;
  return out;
}

/**
 * Reflect-pad by `pad` samples each side — numpy's `np.pad(mode='reflect')`, which is
 * what `spectrogram(center=True)` applies before framing. The edge sample itself is
 * NOT repeated (padded[pad-1] = x[1], not x[0]).
 */
export function reflectPad(x: Float32Array, pad: number): Float64Array {
  const n = x.length;
  const out = new Float64Array(n + 2 * pad);
  for (let i = 0; i < pad; i++) out[i] = x[Math.min(pad - i, n - 1)];
  for (let i = 0; i < n; i++) out[pad + i] = x[i];
  for (let i = 0; i < pad; i++) out[pad + n + i] = x[Math.max(n - 2 - i, 0)];
  return out;
}

/** Lazily-built, reused across calls — the tables and scratch cost more than a frame. */
let fftCache: Fft | null = null;
let windowCache: Float64Array | null = null;
let melCache: MelFilter[] | null = null;

/**
 * The full Whisper log-Mel of an already-normalized `N_SAMPLES` waveform, laid out as
 * the model's `[1, N_MELS, N_FRAMES]` tensor data (mel-major: `mel * N_FRAMES + frame`).
 */
export function logMelSpectrogram(waveform: Float32Array): Float32Array {
  if (waveform.length !== N_SAMPLES) {
    throw new Error(`logMelSpectrogram expects ${N_SAMPLES} samples, got ${waveform.length}`);
  }
  const fft = (fftCache ??= new Fft(N_FFT));
  const window = (windowCache ??= hannWindow(N_FFT));
  const mels = (melCache ??= melFilterBank(N_FFT / 2 + 1, N_MELS, 0.0, 8000.0, SAMPLE_RATE));

  const padded = reflectPad(waveform, N_FFT / 2);
  // Whisper computes one extra frame and then drops it (`log_spec[:, :-1]`), so the
  // last frame's edge-padding artifact never reaches the model.
  const numFrames = 1 + Math.floor((padded.length - N_FFT) / HOP_LENGTH);
  const keptFrames = Math.min(N_FRAMES, numFrames - 1);

  const frameRe = new Float64Array(N_FFT);
  const frameIm = new Float64Array(N_FFT); // stays all-zero: the input is real
  const numBins = N_FFT / 2 + 1;
  const power = new Float64Array(numBins);
  const out = new Float32Array(N_MELS * N_FRAMES);

  let maxLog = -Infinity;
  for (let f = 0; f < keptFrames; f++) {
    const t0 = f * HOP_LENGTH;
    for (let i = 0; i < N_FFT; i++) frameRe[i] = padded[t0 + i] * window[i];
    const spec = fft.transform(frameRe, frameIm);
    for (let k = 0; k < numBins; k++) power[k] = spec.re[k] * spec.re[k] + spec.im[k] * spec.im[k];
    for (let m = 0; m < N_MELS; m++) {
      const filter = mels[m];
      let acc = 0;
      for (let i = 0; i < filter.weights.length; i++) acc += filter.weights[i] * power[filter.start + i];
      const v = Math.log10(Math.max(MEL_FLOOR, acc));
      if (v > maxLog) maxLog = v;
      out[m * N_FRAMES + f] = v;
    }
  }

  // Whisper's dynamic-range compression, over the KEPT frames only.
  const floor = maxLog - 8.0;
  for (let m = 0; m < N_MELS; m++) {
    const row = m * N_FRAMES;
    for (let f = 0; f < keptFrames; f++) out[row + f] = (Math.max(out[row + f], floor) + 4.0) / 4.0;
    // Frames beyond the audio (only possible if the window were short) read as the
    // compressed floor, exactly as a zero-padded waveform would.
    for (let f = keptFrames; f < N_FRAMES; f++) out[row + f] = (floor + 4.0) / 4.0;
  }
  return out;
}

/**
 * Segment → smart-turn v3 `input_features`: the whole chain (last-8s window,
 * zero-mean/unit-var, log-Mel), returning `[1, N_MELS, N_FRAMES]` tensor data.
 *
 * `audio` must already be 16kHz mono — the VAD hands its segments over at exactly
 * that rate, and resampling here would be a silent quality change.
 */
export function whisperFeatures(audio: Float32Array): Float32Array {
  return logMelSpectrogram(zeroMeanUnitVar(fitToWindow(audio)));
}
